### ISSUE TITLE
Raspberry Flight HAT

### ISSUE THREAD

**Issue by velmatoff-hero** [dridri/bcflight#4]
Hello! Great job!
Now I'm looking at the Raspberry Flight HAT and can't figure out why two RFM95W-915S2 modules are used?

**Comment by dridri** [comment]
Hello, the second radio module is not mandatory and is only used for diversity : it decreases the risk of missing transmitted packets to the drone.
If you are about to build the newest HAT with Teensy4 be careful as the code is not finished yet, I currently don't have the time to work on it :/ (but hopping to be back on it in the next months)
