### ISSUE TITLE
flight Build errors! What compiler to use?

### ISSUE THREAD

**Issue by smarkoco** [dridri/bcflight#6]
After installing all suggested dependencies from the Readme, I tried compiling the flight module directly on the RPi4 running Ubuntu 20.04. Unfortunately got some errors related to "unknown parameter '-m32'" and it suggested it couldn't find an arm compiler. I downloaded the below packages on the RPi4:  
- `gcc-arm-linux-gnueabihf`
- `g++-arm-linux-gnueabihf` 

After this, I got a different fatal error, "could not find `WiringPi.h`". I downloaded a [wiringpi](http://wiringpi.com/download-and-install/) package for Ubuntu, but sadly that didn't resolve the error.

What build process would you recommend? Maybe cross compiling on my laptop rather than on the RPi4 itself? Much appreciate any tips 

I think I got some other Cmake errors but I can't remember exactly what those were, more details later

Thanks! (By the way I got the camera so I'm trying to start testing it)

Edit: Ahhh I just realized, maybe I should be using some version of Raspbian?

**Comment by smarkoco** [comment]
Awesome, great resource for cross compilation. I'll try compiling on the RPi4 again this week, this time with the latest Raspbian on the SD card

Still need to get the connectors and waiting on the CM4 I/O board, so for now I'm just trying everything with a regular RPi4B, and later hopefully I can just swap the SD card into the CM4![image](https://user-images.githubusercontent.com/53878603/225046272-b5ba8123-e1b2-408a-b387-9c91d61d0ec7.jpeg)

**Comment by smarkoco** [comment]
Okay, I've just re-flashed the USB drive with Raspbian Bullseye (system info below)
```
System:    Host: flight1 Kernel: 5.15.84-v7l+ armv7l bits: 32 Console: tty 13 Distro: Raspbian GNU/Linux 11 (bullseye) 
Machine:   Type: ARM Device System: Raspberry Pi 4 Model B Rev 1.4 details: BCM2711 rev: d03114 serial: 100000001d0c0fec 
Drives:    Local Storage: total: 14.32 GiB used: 4.21 GiB (29.4%) 
           ID-1: /dev/sda type: USB vendor: SanDisk model: Ultra Fit size: 14.32 GiB 
Info:      Processes: 195 Uptime: 3h 37m Memory: 7.79 GiB used: 1.02 GiB (13.1%) gpu: 76 MiB Init: systemd runlevel: 5 
           Shell: Bash inxi: 3.3.01 
```

I was able to get past the WiringPi.h missing error by following the couple of steps at [this link](http://wiringpi.com/wiringpi-updated-to-2-52-for-the-raspberry-pi-4b/). After that, there was an error with lua similar to [this one](https://github.com/bungle/lua-resty-template/issues/1), which was resolved by updating to `sudo apt install lua5.3`

However, now I've gotten a large amount of errors that I'm not sure how to interpret during the building of libcamera-dev source files. I even uninstalled that and built with the latest release on github, but got a similar slew of errors from all the source files. Based on your experience, any idea why this might be happening in the `make_results.txt` file below? Thanks in advance!

[make_results.txt](https://github.com/dridri/bcflight/files/10986786/make_results.txt)

**Comment by dridri** [comment]
Ah indeed, now that I have upgraded my Raspbian distro I have the same errors. Looking at it

**Comment by dridri** [comment]
Everything should work now. wiringPi has been replaced by pigpio, dependency list has been updated in the [readme](https://github.com/dridri/bcflight#building-flight).
I'm also working on a script to generate pre-built images, and cross-compiling instructions.
